---
- name: "build container with ansible"
  hosts: localhost
  tasks:

  - name: stop running github-project-container
    command: sudo docker stop github-project-container
    ignore_errors: yes
  
  - name: delete github-project-container
    command: sudo docker rm github-project-container
    ignore_errors: yes

  - name: delete github-project-img
    command: sudo docker rmi github-project-img
    ignore_errors: yes

  - name: build github-project-img from dockerfile
    command: sudo docker build -t github-project-img .

  - name: create a tag to github-project-img
    command: sudo docker tag github-project-img wiameelyakini/github-project

  - name: run ansible-container from ansible-img
    command: sudo docker run -d --name ansible-container -p 8087:80 ansible-img


